alibaba/lowcode-engine-ext

src/plugin/plugin-event-bind-dialog/index.tsx, src/setter/events-setter/index.tsx, src/setter/expression-setter/index.tsx, src/setter/i18n-setter/index.tsx, src/setter/mixed-setter/index.tsx, src/setter/number-setter/index.tsx
mixed setter 切换的时候重置 value，另外删掉一些 console
=> reset value when mixed setter change

src/plugin/plugin-event-bind-dialog/index.tsx, src/plugin/plugin-variable-bind-dialog/index.tsx, src/setter/function-setter/index.tsx, src/setter/json-setter/index.tsx, src/setter/style-setter/components/css-code/index.tsx, src/setter/style-setter/components/radio-group/index.tsx, src/setter/style-setter/components/row/index.tsx, src/setter/style-setter/index.tsx, src/setter/style-setter/pro/font/index.tsx, src/setter/style-setter/pro/layout/index.less, src/setter/style-setter/pro/layout/index.tsx, src/setter/style-setter/pro/layout/layoutBox.tsx, src/setter/style-setter/pro/position/index.tsx
增加了style-setter 细粒度的配置，可以更细粒度的控制style-setter展示
=> feat: 新僧style-setter配置

src/components/custom-icon.tsx
问题反馈：https://github.com/alibaba/lowcode-engine/issues/954
=> fix: 修改自定义icon onload没有执行问题

package.json, src/components/custom-icon.tsx, src/setter/classname-setter/index.tsx
修改了list的判空，同时把icon加载换成DOMContentLoaded，避免和window.onload 冲突
=> fix: classname-setter list 判空,icon的onload加载换了一个函数

build.plugin.js, package.json
=> fix: 修正代理调试的时候sourcemap不能映射的问题

src/plugin/plugin-variable-bind-dialog/index.tsx
解这个[弹窗导致 drawer 消失](https://github.com/alibaba/lowcode-engine/issues/843)的问题，依赖[这个引擎 MR ](https://github.com/alibaba/lowcode-engine/pull/966)注入对应的 div
=> feat: fix variable dialog container

src/setter/style-setter/components/number/index.tsx, src/setter/style-setter/pro/border/index.tsx
=> fix: 修复圆角的选中状态问题

src/setter/mixed-setter/index.tsx
如果把 mixed used setter 保存在顶层，拖拽排序后肯定有异常，例如下属性
path: ['config', 0, 'disabled']，config 是一个数组，index 为 0 的对象里面有个 disabled 属性使用 mixed 赋值
_unsafe_MixedSetter_config_0_disabled_select
array setter 拖拽后 index 可能就不是 0 了，所以这个 key 记录的 setter 肯定也就对不上了。
解法：需要把这个 key 保存在 disabled 同级
发现引擎支持直接 field.node.setPropValue(path.join('.'), usedSetter) 赋值和支持 field.node.getPropValue(path.join('.')) 取值，这个问题就好解了。
最后用 oldUnsafeKey 兼容下以前的写法
=> fix: mixed used setter save in same level with prop

src/plugin/plugin-event-bind-dialog/index.tsx
desc:fix event parameter error of new function
=> fix:fix event parameter error of new function

package.json
fixed https://github.com/alibaba/lowcode-engine/issues/1087
=> feat: dependency version unlocked

package.json, src/setter/style-setter/components/css-code/index.tsx
=> fix: 移除codemirror

src/setter/array-setter/index.tsx
使用 onChange、value 替换 field.setValue，可以兼容更多的场景
=> fix: fix variable configuration lost when array setter is used with variable

README.md, package.json, scripts/sync-oss.js
添加  uipaas cdn 支持, 发布后通过调用 tnpm run syncOss 可发布到 uipaas cdn
=> chore: add new cdn support

src/setter/array-setter/index.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1721
fixed https://github.com/alibaba/lowcode-engine/issues/420
问题原因：由于 array-setter 只在 constructor 里面进行初始化，后面使用 api 修改了 value 值也不会再进行初始化。
改成 getDerivedStateFromProps，只根据 value 值的变化，对 items 进行初始化即可。
复现步骤：
1.https://lowcode-engine.cn/demo/demo-general/index.html
2.拖拽一个表格组件
3.在控制台执行 AliLowCodeEngine.project.currentDocument.selection.getNodes()[0].settingEntry.get('actionBar').setValue([{"title": '1'},{title: '2'}, {title: '4'}]) 代码
预期，有三行数据。
可以看到最外层的 value 数组长度为 3，但是只展示了两行。
=> fix: array setter component not change when data was modified using field setValue api

README.md, src/plugin/plugin-variable-bind-dialog/index.tsx, src/setter/style-setter/components/number/index.tsx, src/setter/style-setter/index.tsx
=> feat: 支持拓展变量绑定面板

src/setter/array-setter/index.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1786
=> fix: fix array setter input error

src/setter/array-setter/index.tsx, src/setter/object-setter/index.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1810
=> fix: fix array stter change slot render config error

src/setter/object-setter/index.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1823
=> fix: fix object-setter always create new field

src/setter/array-setter/index.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1845
=> fix: fix array setter sort error

src/plugin/plugin-variable-bind-dialog/index.less
=> style: suport engine css varible

src/index.tsx, src/plugin/plugin-simple-bind-popup/index.less, src/plugin/plugin-simple-bind-popup/index.tsx, src/setter/mixed-setter/index.tsx, src/setter/variable-setter/index.tsx
=> chore: simple-bind-var

src/plugin/plugin-simple-bind-popup/index.tsx, src/setter/mixed-setter/index.tsx
=> chore: uniq setter & ref location

src/plugin/plugin-simple-bind-popup/index.tsx, src/plugin/plugin-simple-bind-popup/utils.ts
=> fix: 简单变量绑定面板位置超出修复
